# This is a basic workflow to help you get started with Actions

name: R Conda

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false      
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-14]
        experimental: [false]
        include:
          - os: macos-14-arm64
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install wget
        if: ${{ matrix.os == 'windows-latest' }}
        run: choco install wget
      - name: Sets env vars for osx-64
        run: echo "CONDA_SUBDIR=osx-64" >> $GITHUB_ENV
        if: ${{ matrix.os == 'macos-14' }}
      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: recetox-waveica-dev
          auto-update-conda: true
          environment-file: conda/environment-dev.yaml
          auto-activate-base: false
      - run: |
          conda init bash
          conda env list
      - name: Fetch input data
        run: | 
          wget -P tests/testthat/test-data -i tests/remote-files/fetch_input_data.txt
          wget -P tests/testthat/test-data/batchwise-correction -i tests/remote-files/fetch_waveica_batchwise.txt
          wget -P tests/testthat/test-data/nonbatchwise-correction -i tests/remote-files/fetch_waveica_nonbatchwise.txt
      - name: setup Rtools
        if: ${{ matrix.os == 'windows-latest' }}
        uses: r-windows/install-rtools@master
      - name: Run devtools::check()
        run: |
          conda activate recetox-waveica-dev
          Rscript -e "devtools::check(error_on = 'error')"

